language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install poppler-utils
virtual_env:
  system_site_packages: true
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script: pytest --cov=pyboleto
after_success: coveralls
deploy:
  provider: pypi
  user: trustcode
  on:
    branch: master3
  password:
    secure: lwd9y+aZKEHwl66Ozv4pa41DK1bh0p3tPV0HM2GDzELTAgtbg5+2BhNqAzQOisgjb99Y4HVQxxFsFtDQo6DL1ze3kuMyrJ7+3uzeX/FpEYqlw/ufb+pfCc0wdy3LsVJFH7pFhD4F45WGFnaJkg3OSCX5YTz9CfEwKDdDMVG6O0tXmyALsfU2rLnM5FoQwV/l5lGDaXO17s9mO02L8kUh68nnrJ6y5CzjOj+K/uuHzSDUIkocauQzdwzw6A1mYtxEYu3uOL1osv/Bb3aHSPd9W8Jp6VBfM21aakZxnROHsNO0g2HEXUju8TUL7XmrOu9llJc9gBG6Iv0p98UoXzQCpiJ8BS9kcbCBQ4lrWbtAUz91Ql+Jmu8CZoq8sCuPypoLp+3iQcTwkKcZTguw7lPQTT1fXR6aA44zxra0miujFDTDdKnHjTHGDNagZd03oq9ciq6ObZXl9N2o/CIymi+ApmpEojG8Ufb/qXVp1VuIllw88wI6w0NG3u2KWQm6qjFg5MGPsA5YvGxZAO6pUT+FBJ/+l3dfA97pg7YgP9Pk/21+ie/5LCOBmbZ7ufQZrrL9mcRsJvSRJMHV+eKrtkt/yvr49os+/HLZpzW9ghO6F+O93BazqsVfTSBffxpSRT1iY9yQu6fNltypCoV52BweqQugF9BpZgUZefgyzhiHFQ8=
  distributions: bdist_wheel
